# Generated by Django 4.0.4 on 2022-06-06 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('time_management', '0007_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
